### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "kasun",
  "email": "testuser",
  "password": "testpassword"
}

### Login with the registered user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}