pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                sh 'npm run builds'
            }
            post {
                success {
                    archiveArtifacts artifacts: 'dist/**'
                }
            }
        }
    }
}